/*This file was generated by NativeWind. Do not edit!*/
const {NativeWindStyleSheet: _NativeWindStyleSheet} = require('nativewind');
_NativeWindStyleSheet.create({
  styles: {
    '*': {
      borderTopWidth: 0,
      borderRightWidth: 0,
      borderBottomWidth: 0,
      borderLeftWidth: 0,
      borderStyle: 'solid',
      borderTopColor: '#e5e7eb',
      borderRightColor: '#e5e7eb',
      borderBottomColor: '#e5e7eb',
      borderLeftColor: '#e5e7eb',
    },
    '': {
      borderTopWidth: 0,
      borderRightWidth: 0,
      borderBottomWidth: 0,
      borderLeftWidth: 0,
      borderStyle: 'solid',
      borderTopColor: '#e5e7eb',
      borderRightColor: '#e5e7eb',
      borderBottomColor: '#e5e7eb',
      borderLeftColor: '#e5e7eb',
    },
    html: {
      lineHeight: 1.5,
      fontFamily: 'ui-sans-serif',
    },
    body: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    hr: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    'abbr:where([title])': {
      textDecorationLine: 'underline',
      textDecorationColor: 'black',
      textDecorationStyle: 'dotted',
    },
    code: {
      fontFamily: 'ui-monospace',
      fontSize: '1em',
    },
    kbd: {
      fontFamily: 'ui-monospace',
      fontSize: '1em',
    },
    samp: {
      fontFamily: 'ui-monospace',
      fontSize: '1em',
    },
    pre: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    small: {
      fontSize: '80%',
    },
    sub: {
      fontSize: '75%',
      lineHeight: 0,
      position: 'relative',
    },
    sup: {
      fontSize: '75%',
      lineHeight: 0,
      position: 'relative',
    },
    button: {
      backgroundColor: 'transparent',
    },
    input: {
      opacity: 1,
      color: '#9ca3af',
    },
    optgroup: {
      fontFamily: 'inherit',
      fontSize: '100%',
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    select: {
      textTransform: 'none',
    },
    textarea: {
      opacity: 1,
      color: '#9ca3af',
    },
    "[type='button']": {
      backgroundColor: 'transparent',
    },
    "[type='reset']": {
      backgroundColor: 'transparent',
    },
    "[type='submit']": {
      backgroundColor: 'transparent',
    },
    ':-moz-ui-invalid': {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'black',
      shadowOpacity: 1,
    },
    blockquote: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    dl: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    dd: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h1: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h2: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h3: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h4: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h5: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h6: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    figure: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    p: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    fieldset: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    legend: {
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    ol: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    ul: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    menu: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    img: {
      maxWidth: '100%',
    },
    video: {
      maxWidth: '100%',
    },
    '[hidden]': {
      display: 'none',
    },
    'shadow-2xl@0': {
      elevation: 25,
      shadowColor: 'rgba(0, 0, 0, 0.1)',
    },
    'shadow-2xl@1': {
      shadowOffset: {
        width: 0,
        height: 25,
      },
      shadowRadius: 50,
      shadowColor: 'rgba(0, 0, 0, 0.1)',
      shadowOpacity: 1,
    },
    'shadow-2xl@2': {
      shadowOffset: {
        width: 0,
        height: 25,
      },
      shadowRadius: 50,
      shadowColor: 'rgba(0, 0, 0, 0.1)',
      shadowOpacity: 1,
    },
    absolute: {
      position: 'absolute',
    },
    relative: {
      position: 'relative',
    },
    'bottom-10': {
      bottom: 40,
    },
    'bottom-20': {
      bottom: 80,
    },
    'bottom-7': {
      bottom: 28,
    },
    'left-0': {
      left: 0,
    },
    'left-[-10px]': {
      left: -10,
    },
    'right-0': {
      right: 0,
    },
    'right-10': {
      right: 40,
    },
    'right-5': {
      right: 20,
    },
    'top-[-10px]': {
      top: -10,
    },
    'top-[85%]': {
      top: '85%',
    },
    'm-0': {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    'm-0.5': {
      marginTop: 2,
      marginRight: 2,
      marginBottom: 2,
      marginLeft: 2,
    },
    'm-1': {
      marginTop: 4,
      marginRight: 4,
      marginBottom: 4,
      marginLeft: 4,
    },
    'm-2': {
      marginTop: 8,
      marginRight: 8,
      marginBottom: 8,
      marginLeft: 8,
    },
    'm-5': {
      marginTop: 20,
      marginRight: 20,
      marginBottom: 20,
      marginLeft: 20,
    },
    'm-auto': {
      marginTop: 'auto',
      marginRight: 'auto',
      marginBottom: 'auto',
      marginLeft: 'auto',
    },
    'mx-1': {
      marginLeft: 4,
      marginRight: 4,
    },
    'mx-2': {
      marginLeft: 8,
      marginRight: 8,
    },
    'mx-3': {
      marginLeft: 12,
      marginRight: 12,
    },
    'mx-4': {
      marginLeft: 16,
      marginRight: 16,
    },
    'mx-5': {
      marginLeft: 20,
      marginRight: 20,
    },
    'mx-6': {
      marginLeft: 24,
      marginRight: 24,
    },
    'mx-auto': {
      marginLeft: 'auto',
      marginRight: 'auto',
    },
    'my-1': {
      marginTop: 4,
      marginBottom: 4,
    },
    'my-2': {
      marginTop: 8,
      marginBottom: 8,
    },
    'my-3': {
      marginTop: 12,
      marginBottom: 12,
    },
    'my-4': {
      marginTop: 16,
      marginBottom: 16,
    },
    'my-6': {
      marginTop: 24,
      marginBottom: 24,
    },
    'mb-0': {
      marginBottom: 0,
    },
    'mb-1': {
      marginBottom: 4,
    },
    'mb-10': {
      marginBottom: 40,
    },
    'mb-2': {
      marginBottom: 8,
    },
    'mb-20': {
      marginBottom: 80,
    },
    'mb-24': {
      marginBottom: 96,
    },
    'mb-4': {
      marginBottom: 16,
    },
    'mb-40': {
      marginBottom: 160,
    },
    'mb-44': {
      marginBottom: 176,
    },
    'mb-52': {
      marginBottom: 208,
    },
    'ml-10': {
      marginLeft: 40,
    },
    'ml-4': {
      marginLeft: 16,
    },
    'ml-6': {
      marginLeft: 24,
    },
    'mr-2': {
      marginRight: 8,
    },
    'mr-6': {
      marginRight: 24,
    },
    'mt-1': {
      marginTop: 4,
    },
    'mt-10': {
      marginTop: 40,
    },
    'mt-2': {
      marginTop: 8,
    },
    'mt-3': {
      marginTop: 12,
    },
    'mt-5': {
      marginTop: 20,
    },
    'mt-6': {
      marginTop: 24,
    },
    'mt-8': {
      marginTop: 32,
    },
    'mt-[-100px]': {
      marginTop: -100,
    },
    flex: {
      display: 'flex',
    },
    'h-0': {
      height: 0,
    },
    'h-0.5': {
      height: 2,
    },
    'h-12': {
      height: 48,
    },
    'h-16': {
      height: 64,
    },
    'h-20': {
      height: 80,
    },
    'h-24': {
      height: 96,
    },
    'h-32': {
      height: 128,
    },
    'h-36': {
      height: 144,
    },
    'h-40': {
      height: 160,
    },
    'h-48': {
      height: 192,
    },
    'h-52': {
      height: 208,
    },
    'h-[100%]': {
      height: '100%',
    },
    'h-[195px]': {
      height: 195,
    },
    'h-[25%]': {
      height: '25%',
    },
    'h-[38%]': {
      height: '38%',
    },
    'h-[50%]': {
      height: '50%',
    },
    'h-[80%]': {
      height: '80%',
    },
    'h-[95%]': {
      height: '95%',
    },
    'h-screen': {
      height: 100,
    },
    'w-1/2': {
      width: '50%',
    },
    'w-11/12': {
      width: '91.666667%',
    },
    'w-12': {
      width: 48,
    },
    'w-14': {
      width: 56,
    },
    'w-16': {
      width: 64,
    },
    'w-20': {
      width: 80,
    },
    'w-24': {
      width: 96,
    },
    'w-3/4': {
      width: '75%',
    },
    'w-3/5': {
      width: '60%',
    },
    'w-32': {
      width: 128,
    },
    'w-4/5': {
      width: '80%',
    },
    'w-44': {
      width: 176,
    },
    'w-[10%]': {
      width: '10%',
    },
    'w-[100%]': {
      width: '100%',
    },
    'w-[15%]': {
      width: '15%',
    },
    'w-[20%]': {
      width: '20%',
    },
    'w-[35%]': {
      width: '35%',
    },
    'w-[38%]': {
      width: '38%',
    },
    'w-[40%]': {
      width: '40%',
    },
    'w-[45%]': {
      width: '45%',
    },
    'w-[50%]': {
      width: '50%',
    },
    'w-[70%]': {
      width: '70%',
    },
    'w-[90%]': {
      width: '90%',
    },
    'w-[90vw]': {
      width: 90,
    },
    'w-screen': {
      width: 100,
    },
    'flex-row': {
      flexDirection: 'row',
    },
    'flex-wrap': {
      flexWrap: 'wrap',
    },
    'items-center': {
      alignItems: 'center',
    },
    'justify-start': {
      justifyContent: 'flex-start',
    },
    'justify-center': {
      justifyContent: 'center',
    },
    'justify-between': {
      justifyContent: 'space-between',
    },
    'justify-around': {
      justifyContent: 'space-around',
    },
    'rounded-2xl': {
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      borderBottomRightRadius: 16,
      borderBottomLeftRadius: 16,
    },
    'rounded-3xl': {
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderBottomRightRadius: 24,
      borderBottomLeftRadius: 24,
    },
    'rounded-full': {
      borderTopLeftRadius: 9999,
      borderTopRightRadius: 9999,
      borderBottomRightRadius: 9999,
      borderBottomLeftRadius: 9999,
    },
    'rounded-lg': {
      borderTopLeftRadius: 8,
      borderTopRightRadius: 8,
      borderBottomRightRadius: 8,
      borderBottomLeftRadius: 8,
    },
    'rounded-md': {
      borderTopLeftRadius: 6,
      borderTopRightRadius: 6,
      borderBottomRightRadius: 6,
      borderBottomLeftRadius: 6,
    },
    'rounded-xl': {
      borderTopLeftRadius: 12,
      borderTopRightRadius: 12,
      borderBottomRightRadius: 12,
      borderBottomLeftRadius: 12,
    },
    border: {
      borderTopWidth: 1,
      borderRightWidth: 1,
      borderBottomWidth: 1,
      borderLeftWidth: 1,
    },
    'border-2': {
      borderTopWidth: 2,
      borderRightWidth: 2,
      borderBottomWidth: 2,
      borderLeftWidth: 2,
    },
    'border-black': {
      borderTopColor: '#000',
      borderRightColor: '#000',
      borderBottomColor: '#000',
      borderLeftColor: '#000',
    },
    'border-gray-100': {
      borderTopColor: '#f3f4f6',
      borderRightColor: '#f3f4f6',
      borderBottomColor: '#f3f4f6',
      borderLeftColor: '#f3f4f6',
    },
    'border-gray-300': {
      borderTopColor: '#d1d5db',
      borderRightColor: '#d1d5db',
      borderBottomColor: '#d1d5db',
      borderLeftColor: '#d1d5db',
    },
    'border-slate-200': {
      borderTopColor: '#e2e8f0',
      borderRightColor: '#e2e8f0',
      borderBottomColor: '#e2e8f0',
      borderLeftColor: '#e2e8f0',
    },
    'bg-[#e1e1e1]': {
      backgroundColor: '#e1e1e1',
    },
    'bg-[#e8e8e8]': {
      backgroundColor: '#e8e8e8',
    },
    'bg-[#eaeaea]': {
      backgroundColor: '#eaeaea',
    },
    'bg-black': {
      backgroundColor: '#000',
    },
    'bg-blue-700': {
      backgroundColor: '#1d4ed8',
    },
    'bg-gray-100': {
      backgroundColor: '#f3f4f6',
    },
    'bg-gray-200': {
      backgroundColor: '#e5e7eb',
    },
    'bg-red-600': {
      backgroundColor: '#dc2626',
    },
    'bg-slate-100': {
      backgroundColor: '#f1f5f9',
    },
    'bg-white': {
      backgroundColor: '#fff',
    },
    'p-1': {
      paddingTop: 4,
      paddingRight: 4,
      paddingBottom: 4,
      paddingLeft: 4,
    },
    'p-2': {
      paddingTop: 8,
      paddingRight: 8,
      paddingBottom: 8,
      paddingLeft: 8,
    },
    'p-3': {
      paddingTop: 12,
      paddingRight: 12,
      paddingBottom: 12,
      paddingLeft: 12,
    },
    'p-4': {
      paddingTop: 16,
      paddingRight: 16,
      paddingBottom: 16,
      paddingLeft: 16,
    },
    'px-10': {
      paddingLeft: 40,
      paddingRight: 40,
    },
    'px-12': {
      paddingLeft: 48,
      paddingRight: 48,
    },
    'px-2': {
      paddingLeft: 8,
      paddingRight: 8,
    },
    'px-3': {
      paddingLeft: 12,
      paddingRight: 12,
    },
    'px-4': {
      paddingLeft: 16,
      paddingRight: 16,
    },
    'px-5': {
      paddingLeft: 20,
      paddingRight: 20,
    },
    'px-6': {
      paddingLeft: 24,
      paddingRight: 24,
    },
    'px-8': {
      paddingLeft: 32,
      paddingRight: 32,
    },
    'px-9': {
      paddingLeft: 36,
      paddingRight: 36,
    },
    'py-1': {
      paddingTop: 4,
      paddingBottom: 4,
    },
    'py-1.5': {
      paddingTop: 6,
      paddingBottom: 6,
    },
    'py-2': {
      paddingTop: 8,
      paddingBottom: 8,
    },
    'py-3': {
      paddingTop: 12,
      paddingBottom: 12,
    },
    'py-3.5': {
      paddingTop: 14,
      paddingBottom: 14,
    },
    'py-4': {
      paddingTop: 16,
      paddingBottom: 16,
    },
    'text-center': {
      textAlign: 'center',
    },
    'text-justify': {
      textAlign: 'justify',
    },
    'font-bold': {
      fontWeight: '700',
    },
    'font-extrabold': {
      fontWeight: '800',
    },
    'font-extralight': {
      fontWeight: '200',
    },
    'font-medium': {
      fontWeight: '500',
    },
    'font-normal': {
      fontWeight: '400',
    },
    'font-semibold': {
      fontWeight: '600',
    },
    'tracking-wider': {
      letterSpacing: 0.5,
    },
    'text-black': {
      color: '#000',
    },
    'text-gray-500': {
      color: '#6b7280',
    },
    'text-gray-600': {
      color: '#4b5563',
    },
    'text-gray-700': {
      color: '#374151',
    },
    'text-gray-800': {
      color: '#1f2937',
    },
    'text-slate-500': {
      color: '#64748b',
    },
    'text-white': {
      color: '#fff',
    },
    'color-black': {
      color: '#000',
    },
    'color-gray-700': {
      color: '#374151',
    },
    'color-white': {
      color: '#fff',
    },
    'gap-2': {
      marginLeft: -8,
      marginTop: -8,
    },
    'gap-2.children@0': {
      marginLeft: 8,
      marginTop: 8,
    },
    'gap-4': {
      marginLeft: -16,
      marginTop: -16,
    },
    'gap-4.children@0': {
      marginLeft: 16,
      marginTop: 16,
    },
    'gap-5': {
      marginLeft: -20,
      marginTop: -20,
    },
    'gap-5.children@0': {
      marginLeft: 20,
      marginTop: 20,
    },
    'gap-6': {
      marginLeft: -24,
      marginTop: -24,
    },
    'gap-6.children@0': {
      marginLeft: 24,
      marginTop: 24,
    },
    'gap-9': {
      marginLeft: -36,
      marginTop: -36,
    },
    'gap-9.children@0': {
      marginLeft: 36,
      marginTop: 36,
    },
    'gap-x-1': {
      marginLeft: -4,
    },
    'gap-x-1.children@0': {
      marginLeft: 4,
    },
    'gap-x-1.5': {
      marginLeft: -6,
    },
    'gap-x-1.5.children@0': {
      marginLeft: 6,
    },
    'gap-x-2': {
      marginLeft: -8,
    },
    'gap-x-2.children@0': {
      marginLeft: 8,
    },
    'text-2xl': {
      fontSize: 24,
      lineHeight: 32,
    },
    'text-3xl': {
      fontSize: 30,
      lineHeight: 36,
    },
    'text-base': {
      fontSize: 16,
      lineHeight: 24,
    },
    'text-lg': {
      fontSize: 18,
      lineHeight: 28,
    },
    'text-sm': {
      fontSize: 14,
      lineHeight: 20,
    },
    'text-xl': {
      fontSize: 20,
      lineHeight: 28,
    },
    'text-xs': {
      fontSize: 12,
      lineHeight: 16,
    },
    'leading-5': {
      lineHeight: 20,
    },
    'leading-8': {
      lineHeight: 32,
    },
    'focus:border-gray-400': {
      borderTopColor: '#9ca3af',
      borderRightColor: '#9ca3af',
      borderBottomColor: '#9ca3af',
      borderLeftColor: '#9ca3af',
    },
  },
  atRules: {
    'shadow-2xl': [
      [['media', 'android']],
      [['media', 'ios']],
      [['media', 'web']],
    ],
    'gap-2.children': [[['selector', '(> *)']]],
    'gap-4.children': [[['selector', '(> *)']]],
    'gap-5.children': [[['selector', '(> *)']]],
    'gap-6.children': [[['selector', '(> *)']]],
    'gap-9.children': [[['selector', '(> *)']]],
    'gap-x-1.children': [[['selector', '(> *)']]],
    'gap-x-1.5.children': [[['selector', '(> *)']]],
    'gap-x-2.children': [[['selector', '(> *)']]],
  },
  masks: {
    'focus:border-gray-400': 512,
  },
  topics: {
    'h-screen': ['height'],
    'w-[90vw]': ['width'],
    'w-screen': ['width'],
  },
  units: {
    'h-screen': {
      height: 'vh',
    },
    'w-[90vw]': {
      width: 'vw',
    },
    'w-screen': {
      width: 'vw',
    },
  },
  childClasses: {
    'gap-2': ['gap-2.children'],
    'gap-4': ['gap-4.children'],
    'gap-5': ['gap-5.children'],
    'gap-6': ['gap-6.children'],
    'gap-9': ['gap-9.children'],
    'gap-x-1': ['gap-x-1.children'],
    'gap-x-1.5': ['gap-x-1.5.children'],
    'gap-x-2': ['gap-x-2.children'],
  },
});
